[color]
background = '#131313'
foreground = '#ffb873'
gradient = 1
gradient_color_1 = '#ffb873'
gradient_color_2 = '#e2c0a4'
gradient_color_3 = '#c1cc99'
gradient_color_4 = '#6a3b00'
gradient_color_5 = '#59422d'
horizontal_gradient = 1
horizontal_gradient_color_1 = '#474747'
horizontal_gradient_color_2 = '#e2c0a4'
horizontal_gradient_color_3 = '#c1cc99'
blend_direction = 'up'