; [general]
; bars = 10
; framerate = 60

; [input]
; method = pipewire
; source = auto

; [output]
; method = raw
; raw_target = /dev/stdout
; data_format = ascii
; ascii_max_range = 7

; [smoothing]
; noise_reduction = 45
[general]
bars = 10
framerate = 60
sensitivity = 80

[input]
method = pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7

[smoothing]
noise_reduction = 20
monstercat = 0
waves = 0