$image = /home/ratul/Pictures/Wallpapers/973967.jpg

$background = rgba(131313ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303030ff)

$inverse_primary = rgba(8c5000ff)

$inverse_surface = rgba(e2e2e2ff)

$on_background = rgba(e2e2e2ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(4b2800ff)

$on_primary_container = rgba(ffdcbfff)

$on_primary_fixed = rgba(2d1600ff)

$on_primary_fixed_variant = rgba(6a3b00ff)

$on_secondary = rgba(412c18ff)

$on_secondary_container = rgba(ffdcbfff)

$on_secondary_fixed = rgba(291806ff)

$on_secondary_fixed_variant = rgba(59422dff)

$on_surface = rgba(e2e2e2ff)

$on_surface_variant = rgba(c6c6c6ff)

$on_tertiary = rgba(2b340fff)

$on_tertiary_container = rgba(dde8b3ff)

$on_tertiary_fixed = rgba(171e00ff)

$on_tertiary_fixed_variant = rgba(424b24ff)

$outline = rgba(919191ff)

$outline_variant = rgba(474747ff)

$primary = rgba(ffb873ff)

$primary_container = rgba(6a3b00ff)

$primary_fixed = rgba(ffdcbfff)

$primary_fixed_dim = rgba(ffb873ff)

$scrim = rgba(000000ff)

$secondary = rgba(e2c0a4ff)

$secondary_container = rgba(59422dff)

$secondary_fixed = rgba(ffdcbfff)

$secondary_fixed_dim = rgba(e2c0a4ff)

$shadow = rgba(000000ff)

$source_color = rgba(806d5dff)

$surface = rgba(131313ff)

$surface_bright = rgba(393939ff)

$surface_container = rgba(1f1f1fff)

$surface_container_high = rgba(2a2a2aff)

$surface_container_highest = rgba(353535ff)

$surface_container_low = rgba(1b1b1bff)

$surface_container_lowest = rgba(0e0e0eff)

$surface_dim = rgba(131313ff)

$surface_tint = rgba(ffb873ff)

$surface_variant = rgba(474747ff)

$tertiary = rgba(c1cc99ff)

$tertiary_container = rgba(424b24ff)

$tertiary_fixed = rgba(dde8b3ff)

$tertiary_fixed_dim = rgba(c1cc99ff)
