cursor            #b0c6ff
cursor_text_color #142e60

foreground            #e2e2e9
background            #0c0e13
selection_foreground  #293042
selection_background  #c0c6dc
url_color             #c0c6dc

#: black 000000 767676
color0  #121318
color8  #33353a
#: red cc0403 f2201f
color1  #0e1f59
color9  #244edc
#: green 19cb00 23fd00
color2  #c0c6dc
color10 #dce2f9
#: yellow cecb00 fffd00
color3  #e0bbde
color11 #fdd7fa
#: blue 0d73cc 1a8fff
color4  #2e4578
color12 #b0c6ff
#: magenta cb1ed1 fd28ff
color5  #404659
color13 #c0c6dc
#: cyan 0dcdcd 14ffff
color6  #593d5a
color14 #e0bbde
#: white dddddd ffffff
color7  #c5c6d0
color15 #e2e2e9

mark1_foreground #001944
mark1_background #d9e2ff
mark2_foreground #141b2c
mark2_background #dce2f9
mark3_foreground #2a132c
mark3_background #fdd7fa

active_tab_foreground #142e60
active_tab_background #b0c6ff
inactive_tab_foreground #d9e2ff
inactive_tab_background #2e4578

active_border_color #b0c6ff
inactive_border_color #142e60
# bell_border_color #ff5a00
