cursor            #ffb873
cursor_text_color #4b2800

foreground            #e2e2e2
background            #0e0e0e
selection_foreground  #412c18
selection_background  #e2c0a4
url_color             #e2c0a4

#: black 000000 767676
color0  #131313
color8  #353535
#: red cc0403 f2201f
color1  #164ba6
color9  #6a9aeb
#: green 19cb00 23fd00
color2  #e2c0a4
color10 #ffdcbf
#: yellow cecb00 fffd00
color3  #c1cc99
color11 #dde8b3
#: blue 0d73cc 1a8fff
color4  #6a3b00
color12 #ffb873
#: magenta cb1ed1 fd28ff
color5  #59422d
color13 #e2c0a4
#: cyan 0dcdcd 14ffff
color6  #424b24
color14 #c1cc99
#: white dddddd ffffff
color7  #c6c6c6
color15 #e2e2e2

mark1_foreground #2d1600
mark1_background #ffdcbf
mark2_foreground #291806
mark2_background #ffdcbf
mark3_foreground #171e00
mark3_background #dde8b3

active_tab_foreground #4b2800
active_tab_background #ffb873
inactive_tab_foreground #ffdcbf
inactive_tab_background #6a3b00

active_border_color #ffb873
inactive_border_color #4b2800
# bell_border_color #ff5a00