[color]
background = '{{colors.surface.default.hex}}'
foreground = '{{colors.primary.default.hex}}'
gradient = 1
gradient_color_1 = '{{colors.primary.default.hex}}'
gradient_color_2 = '{{colors.secondary.default.hex}}'
gradient_color_3 = '{{colors.tertiary.default.hex}}'
gradient_color_4 = '{{colors.primary_container.default.hex}}'
gradient_color_5 = '{{colors.secondary_container.default.hex}}'
horizontal_gradient = 1
horizontal_gradient_color_1 = '{{colors.surface_variant.default.hex}}'
horizontal_gradient_color_2 = '{{colors.secondary.default.hex}}'
horizontal_gradient_color_3 = '{{colors.tertiary.default.hex}}'
blend_direction = 'up'